// Copyright (c) Ultraviolet
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/supermq/pkg/authn"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetAttestationPolicy provides a mock function for the type Service
func (_mock *Service) GetAttestationPolicy(ctx context.Context, session *authn.Session) ([]byte, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for GetAttestationPolicy")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authn.Session) ([]byte, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authn.Session) []byte); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authn.Session) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetAttestationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttestationPolicy'
type Service_GetAttestationPolicy_Call struct {
	*mock.Call
}

// GetAttestationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - session *authn.Session
func (_e *Service_Expecter) GetAttestationPolicy(ctx interface{}, session interface{}) *Service_GetAttestationPolicy_Call {
	return &Service_GetAttestationPolicy_Call{Call: _e.mock.On("GetAttestationPolicy", ctx, session)}
}

func (_c *Service_GetAttestationPolicy_Call) Run(run func(ctx context.Context, session *authn.Session)) *Service_GetAttestationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authn.Session
		if args[1] != nil {
			arg1 = args[1].(*authn.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_GetAttestationPolicy_Call) Return(bytes []byte, err error) *Service_GetAttestationPolicy_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Service_GetAttestationPolicy_Call) RunAndReturn(run func(ctx context.Context, session *authn.Session) ([]byte, error)) *Service_GetAttestationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyRequest provides a mock function for the type Service
func (_mock *Service) ProxyRequest(ctx context.Context, session *authn.Session, path string) error {
	ret := _mock.Called(ctx, session, path)

	if len(ret) == 0 {
		panic("no return value specified for ProxyRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authn.Session, string) error); ok {
		r0 = returnFunc(ctx, session, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_ProxyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyRequest'
type Service_ProxyRequest_Call struct {
	*mock.Call
}

// ProxyRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - session *authn.Session
//   - path string
func (_e *Service_Expecter) ProxyRequest(ctx interface{}, session interface{}, path interface{}) *Service_ProxyRequest_Call {
	return &Service_ProxyRequest_Call{Call: _e.mock.On("ProxyRequest", ctx, session, path)}
}

func (_c *Service_ProxyRequest_Call) Run(run func(ctx context.Context, session *authn.Session, path string)) *Service_ProxyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authn.Session
		if args[1] != nil {
			arg1 = args[1].(*authn.Session)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_ProxyRequest_Call) Return(err error) *Service_ProxyRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_ProxyRequest_Call) RunAndReturn(run func(ctx context.Context, session *authn.Session, path string) error) *Service_ProxyRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Secure provides a mock function for the type Service
func (_mock *Service) Secure() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Secure")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Service_Secure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secure'
type Service_Secure_Call struct {
	*mock.Call
}

// Secure is a helper method to define mock.On call
func (_e *Service_Expecter) Secure() *Service_Secure_Call {
	return &Service_Secure_Call{Call: _e.mock.On("Secure")}
}

func (_c *Service_Secure_Call) Run(run func()) *Service_Secure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Secure_Call) Return(s string) *Service_Secure_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Service_Secure_Call) RunAndReturn(run func() string) *Service_Secure_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttestationPolicy provides a mock function for the type Service
func (_mock *Service) UpdateAttestationPolicy(ctx context.Context, session *authn.Session, policy []byte) error {
	ret := _mock.Called(ctx, session, policy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttestationPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authn.Session, []byte) error); ok {
		r0 = returnFunc(ctx, session, policy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_UpdateAttestationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttestationPolicy'
type Service_UpdateAttestationPolicy_Call struct {
	*mock.Call
}

// UpdateAttestationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - session *authn.Session
//   - policy []byte
func (_e *Service_Expecter) UpdateAttestationPolicy(ctx interface{}, session interface{}, policy interface{}) *Service_UpdateAttestationPolicy_Call {
	return &Service_UpdateAttestationPolicy_Call{Call: _e.mock.On("UpdateAttestationPolicy", ctx, session, policy)}
}

func (_c *Service_UpdateAttestationPolicy_Call) Run(run func(ctx context.Context, session *authn.Session, policy []byte)) *Service_UpdateAttestationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authn.Session
		if args[1] != nil {
			arg1 = args[1].(*authn.Session)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_UpdateAttestationPolicy_Call) Return(err error) *Service_UpdateAttestationPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_UpdateAttestationPolicy_Call) RunAndReturn(run func(ctx context.Context, session *authn.Session, policy []byte) error) *Service_UpdateAttestationPolicy_Call {
	_c.Call.Return(run)
	return _c
}
