# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

FROM scratch
ARG SVC=proxy
COPY cube-${SVC} /exe
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/exe"]
