# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

# Dynamic Traefik Configuration for Cube + ATOM.

[http.middlewares.retry-middleware.retry]
  attempts = 4
  initialInterval = "100ms"

[http.middlewares.headers-middleware.headers]
  frameDeny = true
  browserXssFilter = true

[http.middlewares.strip-proxy-prefix-middleware.stripPrefix]
  prefixes = ["/proxy"]

[http.middlewares.strip-atom-prefix-middleware.stripPrefix]
  prefixes = ["/atom"]

[http.services.proxy.loadBalancer]
  [[http.services.proxy.loadBalancer.servers]]
    url = "http://cube-proxy:8900"
  [http.services.proxy.loadBalancer.healthCheck]
    scheme = "http"
    path = "/health"
    interval = "10s"
    timeout = "10s"

[http.services.ui.loadBalancer]
  [[http.services.ui.loadBalancer.servers]]
    url = "http://cube-ui:5173"
  [http.services.ui.loadBalancer.healthCheck]
    scheme = "http"
    path = "/health"
    interval = "10s"
    timeout = "10s"

[http.services.atom.loadBalancer]
  [[http.services.atom.loadBalancer.servers]]
    url = "http://atom:8080"
  [http.services.atom.loadBalancer.healthCheck]
    scheme = "http"
    path = "/health"
    interval = "10s"
    timeout = "10s"

[http.services.atom-ui.loadBalancer]
  [[http.services.atom-ui.loadBalancer.servers]]
    url = "http://atom-ui:3000"

[http.routers.cube-ui-bff]
  rule = "PathPrefix(`/ui`)"
  entryPoints = ["websecure"]
  service = "proxy"
  middlewares = ["retry-middleware", "headers-middleware"]
  priority = 20

[http.routers.proxy]
  rule = "PathPrefix(`/proxy`)"
  entryPoints = ["websecure"]
  service = "proxy"
  middlewares = ["strip-proxy-prefix-middleware", "retry-middleware", "headers-middleware"]
  priority = 19

[http.routers.cube-runtime]
  rule = "PathPrefix(`/api`) || PathRegexp(`^/[a-f0-9-]+/api`) || PathRegexp(`^/[a-f0-9-]+/attestation`) || PathRegexp(`^/[a-f0-9-]+/guardrails`)"
  entryPoints = ["websecure"]
  service = "proxy"
  middlewares = ["retry-middleware", "headers-middleware"]
  priority = 18

[http.routers.atom-certs]
  rule = "PathPrefix(`/certs`)"
  entryPoints = ["websecure"]
  service = "atom"
  middlewares = ["retry-middleware", "headers-middleware"]
  priority = 15

[http.routers.atom-ui]
  rule = "PathPrefix(`/atom`)"
  entryPoints = ["websecure"]
  service = "atom-ui"
  middlewares = ["strip-atom-prefix-middleware", "retry-middleware", "headers-middleware"]
  priority = 10

[http.routers.ui]
  rule = "PathPrefix(`/`)"
  entryPoints = ["websecure"]
  service = "ui"
  middlewares = ["retry-middleware", "headers-middleware"]
  priority = 1
