# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  compress: true
  format: json
  level: ERROR

accessLog:
  format: json

tracing:
  otlp:
    http:
      endpoint: http://jaeger:4318/v1/traces

api:
  dashboard: false # Change to true for development
  debug: true
  disabledashboardad: true
  insecure: false # Change to true for development

providers:
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: info@ultraviolet.com
      storage: /etc/traefik/ssl/acme.json
      httpChallenge:
        entryPoint: web
