# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.0
info:
  title: Cube Guardrails API
  description: API for managing guardrail configurations and processing chat completions through NeMo Guardrails
  version: 1.0.0
  contact:
    name: Ultraviolet
    url: https://github.com/ultravioletrs/cube

servers:
  - url: http://localhost:8001
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /v1/chat/completions:
    post:
      summary: Process chat completion through guardrails
      description: Process a chat completion request through the NeMo Guardrails runtime
      operationId: chatCompletion
      tags:
        - Chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat completion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletionResponse'
        '503':
          description: Guardrails runtime not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      summary: Health check
      description: Health check endpoint for container monitoring
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /:
    get:
      summary: Root endpoint
      description: Root endpoint with service information
      operationId: root
      tags:
        - Health
      responses:
        '200':
          description: Service information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootResponse'

  /admin/{domain_id}/configs:
    post:
      summary: Create a new guardrail configuration
      description: Create a new guardrail configuration for a domain
      operationId: createConfig
      tags:
        - Configs
      parameters:
        - $ref: '#/components/parameters/domainId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigCreate'
      responses:
        '200':
          description: Configuration created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Domain not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List guardrail configurations
      description: List all guardrail configurations for a domain
      operationId: listConfigs
      tags:
        - Configs
      parameters:
        - $ref: '#/components/parameters/domainId'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: List of configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigResponse'
        '404':
          description: Domain not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /admin/{domain_id}/configs/{config_id}:
    get:
      summary: Get a guardrail configuration
      description: Get a guardrail configuration by ID
      operationId: getConfig
      tags:
        - Configs
      parameters:
        - $ref: '#/components/parameters/domainId'
        - $ref: '#/components/parameters/configId'
      responses:
        '200':
          description: Configuration details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResponse'
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a guardrail configuration
      description: Update an existing guardrail configuration
      operationId: updateConfig
      tags:
        - Configs
      parameters:
        - $ref: '#/components/parameters/domainId'
        - $ref: '#/components/parameters/configId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigUpdate'
      responses:
        '200':
          description: Configuration updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a guardrail configuration
      description: Delete a guardrail configuration by ID
      operationId: deleteConfig
      tags:
        - Configs
      parameters:
        - $ref: '#/components/parameters/domainId'
        - $ref: '#/components/parameters/configId'
      responses:
        '200':
          description: Configuration deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: deleted
                  config_id:
                    type: string
                    format: uuid
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /admin/{domain_id}/configs/{config_id}/versions:
    post:
      summary: Create a new version
      description: Create a new version for a configuration
      operationId: createVersion
      tags:
        - Versions
      parameters:
        - $ref: '#/components/parameters/domainId'
        - $ref: '#/components/parameters/configId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VersionCreate'
      responses:
        '200':
          description: Version created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List versions
      description: List all versions for a configuration
      operationId: listVersions
      tags:
        - Versions
      parameters:
        - $ref: '#/components/parameters/domainId'
        - $ref: '#/components/parameters/configId'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: List of versions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VersionResponse'
        '404':
          description: Configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /admin/{domain_id}/versions/{version_id}/activate:
    post:
      summary: Activate a version
      description: Activate a guardrail version and reload the runtime
      operationId: activateVersion
      tags:
        - Versions
      parameters:
        - $ref: '#/components/parameters/domainId'
        - name: version_id
          in: path
          required: true
          description: The version ID to activate
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Version activated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateResponse'
        '404':
          description: Version not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Activation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /admin/{domain_id}/reload:
    post:
      summary: Reload the runtime
      description: Reload the runtime with the active configuration
      operationId: reloadRuntime
      tags:
        - Admin
      parameters:
        - $ref: '#/components/parameters/domainId'
      responses:
        '200':
          description: Reload status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReloadResponse'

components:
  parameters:
    domainId:
      name: domain_id
      in: path
      required: true
      description: The domain ID
      schema:
        type: string
        format: uuid

    configId:
      name: config_id
      in: path
      required: true
      description: The configuration ID
      schema:
        type: string
        format: uuid

    offset:
      name: offset
      in: query
      required: false
      description: Number of items to skip
      schema:
        type: integer
        minimum: 0
        default: 0

    limit:
      name: limit
      in: query
      required: false
      description: Maximum number of items to return
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 100

  schemas:
    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          description: The role of the message author
          example: user
        content:
          type: string
          description: The content of the message
          example: Hello, how are you?

    ChatRequest:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          description: List of chat messages
          items:
            $ref: '#/components/schemas/ChatMessage'
        temperature:
          type: number
          description: Sampling temperature
          default: 0.1
          minimum: 0
          maximum: 2
          example: 0.1
        max_tokens:
          type: integer
          description: Maximum tokens to generate
          default: 150
          example: 150

    ChatChoice:
      type: object
      properties:
        index:
          type: integer
          example: 0
        message:
          $ref: '#/components/schemas/ChatMessage'
        finish_reason:
          type: string
          example: stop

    ChatUsage:
      type: object
      properties:
        prompt_tokens:
          type: integer
          example: 0
        completion_tokens:
          type: integer
          example: 0
        total_tokens:
          type: integer
          example: 0

    ChatCompletionResponse:
      type: object
      properties:
        id:
          type: string
          example: chatcmpl-guardrails
        object:
          type: string
          example: chat.completion
        created:
          type: integer
          example: 0
        choices:
          type: array
          items:
            $ref: '#/components/schemas/ChatChoice'
        usage:
          $ref: '#/components/schemas/ChatUsage'

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: healthy
        version:
          type: string
          example: "1.0.0"
        runtime_ready:
          type: boolean
          example: true
        current_revision:
          type: integer
          example: 1

    RootResponse:
      type: object
      properties:
        service:
          type: string
          example: Nemo Guardrails API
        version:
          type: string
          example: "1.0.0"
        status:
          type: string
          example: running
        runtime_ready:
          type: boolean
          example: true
        current_revision:
          type: integer
          example: 1
        endpoints:
          type: array
          items:
            type: string
          example:
            - /v1/chat/completions
            - /health
            - /docs
            - /admin/configs
            - /admin/versions/{version_id}/activate
            - /admin/reload

    ConfigCreate:
      type: object
      required:
        - name
        - config_yaml
      properties:
        name:
          type: string
          description: Unique name for the configuration
          minLength: 1
          maxLength: 255
          example: my-guardrail
        description:
          type: string
          description: Optional description
          example: Production guardrail configuration
        config_yaml:
          type: string
          description: YAML content for config.yml
          minLength: 1
          example: |
            models:
              - type: main
                engine: ollama
                model: tinyllama
        prompts_yaml:
          type: string
          description: YAML content for prompts.yml
          default: ""
        colang:
          type: string
          description: Colang content for rails
          default: ""

    ConfigUpdate:
      type: object
      properties:
        name:
          type: string
          description: Updated name
          minLength: 1
          maxLength: 255
        description:
          type: string
          description: Updated description
        config_yaml:
          type: string
          description: Updated YAML content for config.yml
          minLength: 1
        prompts_yaml:
          type: string
          description: Updated YAML content for prompts.yml
        colang:
          type: string
          description: Updated Colang content

    ConfigResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Configuration ID
        domain_id:
          type: string
          format: uuid
          description: Domain ID
        name:
          type: string
          description: Configuration name
        description:
          type: string
          nullable: true
          description: Configuration description
        config_yaml:
          type: string
          description: YAML content for config.yml
        prompts_yaml:
          type: string
          description: YAML content for prompts.yml
        colang:
          type: string
          description: Colang content
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    VersionCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Version name
          minLength: 1
          maxLength: 255
          example: v1.0.0
        description:
          type: string
          description: Optional description
          example: Initial release

    VersionResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Version ID
        config_id:
          type: string
          format: uuid
          description: Parent configuration ID
        name:
          type: string
          description: Version name
        revision:
          type: integer
          description: Revision number
          example: 1
        is_active:
          type: boolean
          description: Whether this version is active
          example: false
        description:
          type: string
          nullable: true
          description: Version description
        created_at:
          type: string
          format: date-time
          description: Creation timestamp

    ActivateResponse:
      type: object
      properties:
        status:
          type: string
          example: activated
        version_id:
          type: string
          format: uuid
        revision:
          type: integer
          example: 1

    ReloadResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        revision:
          type: integer
          example: 1
        message:
          type: string
          example: Reloaded configuration revision 1

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message

tags:
  - name: Chat
    description: Chat completion endpoints with guardrails
  - name: Health
    description: Health check and service information endpoints
  - name: Configs
    description: Guardrail configuration management
  - name: Versions
    description: Configuration version management
  - name: Admin
    description: Administrative operations