# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.0
info:
  title: Cube Proxy - Request Forwarding API
  description: |
    API for forwarding requests to backend services (including the agent) through the Cube proxy with dynamic routing.

    All requests to the agent service, including attestation requests, are routed through this API. The proxy uses
    routing rules to determine the target backend service based on request characteristics.

    Supports all HTTP methods (GET, POST, PUT, DELETE, PATCH) and can forward requests to any configured backend service.
  version: 1.0.0
  contact:
    name: Ultraviolet
    url: https://github.com/ultravioletrs/cube

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /{domainID}/attestation:
    post:
      summary: Generate attestation report
      description: |
        Generates an attestation report from the agent. This endpoint is routed to the agent service
        through the proxy's dynamic routing system.

        The attestation type is automatically determined by the agent's running environment
        (e.g., SEV-SNP, TDX, or vTPM).
        Reports can be returned as JSON (when supported) or binary format.
      operationId: generateAttestation
      tags:
        - Attestation
      security:
        - bearerAuth: []
      parameters:
        - name: domainID
          in: path
          required: true
          description: The domain identifier for routing context
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttestationRequest"
      responses:
        "200":
          description: Attestation report generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttestationResponse"
            application/octet-stream:
              schema:
                type: string
                format: binary
                description: Binary attestation report (when to_json is false and format is binary)
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway - agent service unreachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Attestation generation failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{domainID}/{path}:
    get:
      summary: Forward GET request to backend service
      description: |
        Forwards a GET request to a backend service based on the routing rules defined for this domain.

        Examples of requests that can be forwarded:
        - GET /{domainID}/health - Health check on backend service
        - GET /{domainID}/api/resources - Fetch resources from backend
      operationId: forwardGetRequest
      tags:
        - Request Forwarding
      security:
        - bearerAuth: []
      parameters:
        - name: domainID
          in: path
          required: true
          description: The domain identifier for routing context
          schema:
            type: string
        - name: path
          in: path
          required: true
          description: The request path to be forwarded to the backend
          style: simple
          schema:
            type: string
            default: "/"
        - name: Accept
          in: header
          description: Content type accepted by the client
          schema:
            type: string
            default: "application/json"
      responses:
        "200":
          description: Request forwarded successfully
          content:
            application/json:
              schema:
                type: object
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway - target service unreachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Forward POST request to backend service
      description: |
        Forwards a POST request to a backend service based on the routing rules defined for this domain.

        Examples of requests that can be forwarded:
        - POST /{domainID}/attestation - Generate attestation report from agent
        - POST /{domainID}/api/resources - Create resource in backend
        - POST /{domainID}/invoke - Invoke a function in backend
      operationId: forwardPostRequest
      tags:
        - Request Forwarding
      security:
        - bearerAuth: []
      parameters:
        - name: domainID
          in: path
          required: true
          description: The domain identifier for routing context
          schema:
            type: string
        - name: path
          in: path
          required: true
          description: The request path to be forwarded to the backend
          style: simple
          schema:
            type: string
            default: "/"
        - name: Content-Type
          in: header
          description: Content type of the request body
          schema:
            type: string
            default: "application/json"
      requestBody:
        description: Request body to forward to backend
        content:
          application/json:
            schema:
              type: object
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Request forwarded successfully
          content:
            application/json:
              schema:
                type: object
            application/octet-stream:
              schema:
                type: string
                format: binary
        "201":
          description: Resource created
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway - target service unreachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Forward PUT request to backend service
      description: |
        Forwards a PUT request to a backend service based on the routing rules defined for this domain.

        This can be used for updating resources on backend services reachable through the agent or direct connections.
      operationId: forwardPutRequest
      tags:
        - Request Forwarding
      security:
        - bearerAuth: []
      parameters:
        - name: domainID
          in: path
          required: true
          description: The domain identifier for routing context
          schema:
            type: string
        - name: path
          in: path
          required: true
          description: The request path to be forwarded to the backend
          style: simple
          schema:
            type: string
            default: "/"
        - name: Content-Type
          in: header
          description: Content type of the request body
          schema:
            type: string
            default: "application/json"
      requestBody:
        description: Request body to forward to backend
        content:
          application/json:
            schema:
              type: object
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Request forwarded successfully
          content:
            application/json:
              schema:
                type: object
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway - target service unreachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Forward DELETE request to backend service
      description: |
        Forwards a DELETE request to a backend service based on the routing rules defined for this domain.

        This can be used for deleting resources on backend services reachable through the agent or direct connections.
      operationId: forwardDeleteRequest
      tags:
        - Request Forwarding
      security:
        - bearerAuth: []
      parameters:
        - name: domainID
          in: path
          required: true
          description: The domain identifier for routing context
          schema:
            type: string
        - name: path
          in: path
          required: true
          description: The request path to be forwarded to the backend
          style: simple
          schema:
            type: string
            default: "/"
      responses:
        "200":
          description: Request forwarded successfully
          content:
            application/json:
              schema:
                type: object
        "204":
          description: No content - resource deleted
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway - target service unreachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Forward PATCH request to backend service
      description: |
        Forwards a PATCH request to a backend service based on the routing rules defined for this domain.

        This can be used for partially updating resources on backend services reachable through the agent or direct connections.
      operationId: forwardPatchRequest
      tags:
        - Request Forwarding
      security:
        - bearerAuth: []
      parameters:
        - name: domainID
          in: path
          required: true
          description: The domain identifier for routing context
          schema:
            type: string
        - name: path
          in: path
          required: true
          description: The request path to be forwarded to the backend
          style: simple
          schema:
            type: string
            default: "/"
        - name: Content-Type
          in: header
          description: Content type of the request body
          schema:
            type: string
            default: "application/json"
      requestBody:
        description: Request body to forward to backend
        content:
          application/json:
            schema:
              type: object
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Request forwarded successfully
          content:
            application/json:
              schema:
                type: object
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway - target service unreachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    AttestationRequest:
      type: object
      properties:
        report_data:
          type: string
          format: byte
          description: |
            Base64-encoded report data (nonce) for attestation.
            Must be base64-encoded 64 bytes or less.
            This is used as input to the quote provider for attestation.
          example: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
        nonce:
          type: string
          format: byte
          description: |
            Base64-encoded nonce for vTPM attestation.
            Must be base64-encoded 32 bytes or less.
            Used when attestation_type includes vTPM support.
          example: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

        to_json:
          type: boolean
          description: |
            Whether to return the report as JSON (when supported) or binary format.
            If true and the attestation type supports JSON serialization, the report
            will be returned as JSON. Otherwise, it will be returned as binary.
          example: false

    AttestationResponse:
      type: object
      properties:
        report:
          type: string
          format: byte
          description: |
            The attestation report.
            When to_json is false or the format doesn't support JSON, this will be
            base64-encoded binary data. When to_json is true and the format supports JSON,
            this will be the JSON representation of the report.

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer token authentication

tags:
  - name: Attestation
    description: Attestation report generation endpoints
  - name: Request Forwarding
    description: Dynamic request forwarding endpoints
