name: Create and publish Cube UI Docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - ".github/workflows/ui-cd.yaml"
      - "ui/**"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image-ui:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch tags for the build
        run: |
          git fetch --prune --unshallow --tags

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd ui
          make latest
